[project]
name = "dap-types"
version = "1!1.70"
description = "Debugger Adapter Protocol types for Python."
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.10.6",
]

[dependency-groups]
dev = [
    "datamodel-code-generator>=0.28.4",
]
